/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module alu4bit(a, b, op, result, carry, zero);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output carry;
  wire carry;
  input [2:0] op;
  wire [2:0] op;
  output [3:0] result;
  wire [3:0] result;
  output zero;
  wire zero;
  sky130_fd_sc_hd__and3b_1 _056_ (
    .A_N(op[2]),
    .B(op[1]),
    .C(op[0]),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _057_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _058_ (
    .A(op[1]),
    .B(op[0]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3b_1 _059_ (
    .A(op[2]),
    .B(op[1]),
    .C_N(op[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21a_1 _060_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_001_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o22ai_1 _061_ (
    .A1(a[0]),
    .A2(b[0]),
    .B1(_000_),
    .B2(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and3_1 _062_ (
    .A(op[2]),
    .B(op[1]),
    .C(op[0]),
    .X(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _063_ (
    .A(a[1]),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3b_1 _064_ (
    .A(op[2]),
    .B(op[0]),
    .C_N(op[1]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3_1 _065_ (
    .A(a[0]),
    .B(b[0]),
    .C(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand3b_1 _066_ (
    .A_N(op[1]),
    .B(op[0]),
    .C(op[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o2111ai_1 _067_ (
    .A1(a[0]),
    .A2(_010_),
    .B1(_009_),
    .C1(_007_),
    .D1(_005_),
    .Y(result[0])
  );
  sky130_fd_sc_hd__nand2_1 _068_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _069_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2b_1 _070_ (
    .A_N(a[0]),
    .B(b[0]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xor2_1 _071_ (
    .A(_012_),
    .B(_013_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _072_ (
    .A(op[2]),
    .B(op[1]),
    .C(op[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o21ai_0 _073_ (
    .A1(_001_),
    .A2(_012_),
    .B1(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _074_ (
    .A1(_001_),
    .A2(_012_),
    .B1(_016_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _075_ (
    .A1(_003_),
    .A2(_014_),
    .B1(_017_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _076_ (
    .A(op[2]),
    .B(_002_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o22ai_1 _077_ (
    .A1(a[1]),
    .A2(_010_),
    .B1(_012_),
    .B2(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__and3b_1 _078_ (
    .A_N(op[0]),
    .B(op[1]),
    .C(op[2]),
    .X(_021_)
  );
  sky130_fd_sc_hd__a221oi_1 _079_ (
    .A1(a[2]),
    .A2(_006_),
    .B1(_021_),
    .B2(a[0]),
    .C1(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand3_1 _080_ (
    .A(a[1]),
    .B(b[1]),
    .C(_008_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21ai_0 _081_ (
    .A1(a[1]),
    .A2(b[1]),
    .B1(_000_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand4_1 _082_ (
    .A(_018_),
    .B(_022_),
    .C(_023_),
    .D(_024_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__xor2_1 _083_ (
    .A(a[2]),
    .B(b[2]),
    .X(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _084_ (
    .A(a[1]),
    .SLEEP(b[1]),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _085_ (
    .A1(_012_),
    .A2(_013_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xor2_1 _086_ (
    .A(_025_),
    .B(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _087_ (
    .A(_003_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o21ai_0 _088_ (
    .A1(_001_),
    .A2(_012_),
    .B1(_011_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _089_ (
    .A(_025_),
    .B(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _090_ (
    .A(_015_),
    .B(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a32oi_1 _091_ (
    .A1(a[2]),
    .A2(b[2]),
    .A3(_008_),
    .B1(_021_),
    .B2(a[1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand3_1 _092_ (
    .A(op[2]),
    .B(_002_),
    .C(_025_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _093_ (
    .A1(a[2]),
    .A2(b[2]),
    .B1(_000_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(a[3]),
    .B(_006_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(a[2]),
    .A2(_010_),
    .B1(_034_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand3_1 _096_ (
    .A(_033_),
    .B(_035_),
    .C(_036_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand3_1 _098_ (
    .A(_029_),
    .B(_032_),
    .C(_039_),
    .Y(result[2])
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _100_ (
    .A_N(b[2]),
    .B(a[2]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_025_),
    .A2(_027_),
    .B1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _102_ (
    .A(_040_),
    .SLEEP(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__a21boi_0 _103_ (
    .A1(_040_),
    .A2(_042_),
    .B1_N(_003_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__maj3_1 _104_ (
    .A(a[2]),
    .B(b[2]),
    .C(_030_),
    .X(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _105_ (
    .A(_040_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _106_ (
    .A(a[3]),
    .B(b[3]),
    .C(_008_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _107_ (
    .A1(_019_),
    .A2(_040_),
    .B1(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(a[3]),
    .B(_010_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(a[2]),
    .B(_021_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(a[3]),
    .A2(b[3]),
    .B1(_000_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand4bb_1 _111_ (
    .A_N(_048_),
    .B_N(_049_),
    .C(_050_),
    .D(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a221o_1 _112_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_046_),
    .B2(_015_),
    .C1(_052_),
    .X(result[3])
  );
  sky130_fd_sc_hd__nor4_1 _113_ (
    .A(result[0]),
    .B(result[1]),
    .C(result[2]),
    .D(result[3]),
    .Y(zero)
  );
  sky130_fd_sc_hd__nand2b_1 _114_ (
    .A_N(b[3]),
    .B(a[3]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__maj3_1 _115_ (
    .A(a[3]),
    .B(b[3]),
    .C(_045_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a22o_1 _116_ (
    .A1(a[3]),
    .A2(_021_),
    .B1(_054_),
    .B2(_015_),
    .X(_055_)
  );
  sky130_fd_sc_hd__a21o_1 _117_ (
    .A1(_044_),
    .A2(_053_),
    .B1(_055_),
    .X(carry)
  );
endmodule
